/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4043cdcda067e7a55a6335d3945b28b7)
interface __BaseEnv_Env {
  ASSEMBLYAI_API_KEY: string;
  OPENAI_API_KEY: string;
  CARTESIA_API_KEY: string;
  AssemblyAIVoiceAgent: DurableObjectNamespace<
    import("./src/server").AssemblyAIVoiceAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AssemblyAIVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "ASSEMBLYAI_API_KEY" | "OPENAI_API_KEY" | "CARTESIA_API_KEY"
    >
  > {}
}
