/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3fc99f430cf9974554a26e20487df1e3)
interface __BaseEnv_Env {
  AI: Ai;
  ASSEMBLYAI_API_KEY: string;
  OPENAI_API_KEY: string;
  AssemblyAIVoiceAgent: DurableObjectNamespace<
    import("./src/server").AssemblyAIVoiceAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AssemblyAIVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ASSEMBLYAI_API_KEY" | "OPENAI_API_KEY">
  > {}
}
